# Builds the site and deploys it.
name: Build and Deploy

# Triggers the workflow on push for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: setup
        run: npm ci --prod

      - name: build
        run: npm run build

      - name: verify built output
        run: find build/ -print